### ISSUE TITLE
require.resolve is not a function

### ISSUE THREAD

**Issue by Dinuz** [vu3th/vue-dapp-starter#5]
Unfortunately require.resolve in vite doesn't really work, and it gives an error at launch.
Moreover the whole modal never triggered).

check this https://github.com/vitejs/vite/issues/4385#issuecomment-892106051

I would suggest to just use import nodePolyfills from 'vite-plugin-node-stdlib-browser' and add that to the plugins.

**Comment by chnejohnson** [comment]
I'm not using `require.resolve` in the app but only using it in the `vite.config.ts > optimizeDeps.esbuildOptions.inject`

The configuration works fine for me. Can you tell me how to reproduce your problem?

**Comment by Dinuz** [comment]
I am using vite with vuejs, and in vite.config i cannot use require.resolve as I said before.
To reproduce it just create a new vue/vite project and try to add require.resolve in vite.config.
Ps I am using Js not Ts

**Comment by chnejohnson** [comment]
@Dinuz Try this new configuration
https://github.com/chnejohnson/vue3-dapp-starter/blob/9df8fc84909a1ee4476be1e9ea089f25a549d368/vite.config.ts#L7-L34
